tag CI messages with "CI: "

diff --git a/container-files/ci_tests/run_tests b/container-files/ci_tests/run_tests
--- a/container-files/ci_tests/run_tests
+++ b/container-files/ci_tests/run_tests
@@ -11,13 +11,13 @@ execute_tests() {
   if [ -d "${FUNCTION_INPUT}" ]; then                  # Test that it is a directory
   echo -e "\e[1m" # Style: bold
   echo -e "\e[33m" # Text Color: Yellow
-  echo "running tests in ${FUNCTION_INPUT}/"
+  echo "CI: running tests in ${FUNCTION_INPUT}/"
   echo -e "\e[0m" # Reset all shell attributes
   for FILE in ${FUNCTION_INPUT}/*; do      # Walk through items in the directory
   if [ -x ${FILE} ] && [ -f ${FILE} ]; then       # Make sure it is executable and a file
   echo -e "\e[1m" # Style: bold
   echo -e "\e[33m" # Text Color: Yellow
-  echo "executing test: ${FILE}"
+  echo "CI: executing test: ${FILE}"
   echo -e "\e[0m" # Reset all shell attributes
   ${FILE}                                   # Execute the test
   # $? gives us the exit code of the previous process (last file to run)
@@ -29,19 +29,19 @@ execute_tests() {
   echo -e "\e[1m" # Style: bold
   echo -e "\e[5m" # Style: blink
   echo -e "\e[31m" # Text Color: Red
-  echo "${FILE} exited with non-zero exit code"
+  echo "CI: ${FILE} exited with non-zero exit code"
   echo -e "\e[0m" # Reset all shell attributes
   exit ${RC};                             # Exit and return the non-zero exit code
 else                                      # Test passed
   echo -e "\e[1m" # Style: bold
   echo -e "\e[32m" # Text Color: Green
-  echo "${FILE} test passed"
+  echo "CI: ${FILE} test passed"
   echo -e "\e[0m" # Reset all shell attributes
 fi # end test failed
 else # not executable or a file
   echo -e "\e[1m" # Style: bold
   echo -e "\e[35m" # Text Color: Magenta
-  echo "skipping ${FILE} because it is not executable or not a file"
+  echo "CI: skipping ${FILE} because it is not executable or not a file"
   echo -e "\e[0m" # Reset all shell attributes
 fi # end executable test
 done # end of items in directory
@@ -53,27 +53,27 @@ if [ $# -eq 0 ]; then
   TESTS="all"
   echo -e "\e[1m" # Style: bold
   echo -e "\e[33m" # Text Color: Yellow
-  echo -e "No tests supplied running all tests"
+  echo -e "CI: No tests supplied running all tests"
   echo -e "\e[0m" # Reset all shell attributes
 else # use input as test directory
   TESTS=$1
   if [[ ${TESTS} == "all" ]]; then
     echo -e "\e[1m" # Style: bold
     echo -e "\e[33m" # Text Color: Yellow
-    echo -e "All tests will be run"
+    echo -e "CI: All tests will be run"
     echo -e "\e[0m" # Reset all shell attributes
-    [ ! -d /ci_tests/all ] || echo -e "\e[1m\e[35mWarning: a test directory /ci_tests/all exists, this may not work as you want\e[0m"
+    [ ! -d /ci_tests/all ] || echo -e "\e[1m\e[35mCI: Warning: a test directory /ci_tests/all exists, this may not work as you want\e[0m"
   else
     if [ -d /ci_tests/${TESTS} ]; then
       echo -e "\e[1m" # Style: bold
       echo -e "\e[33m" # Text Color: Yellow
-      echo -e "running tests only from /ci_tests/${TESTS}/"
+      echo -e "CI: running tests only from /ci_tests/${TESTS}/"
       echo -e "\e[0m" # Reset all shell attributes
     else
       echo -e "\e[1m" # Style: bold
       echo -e "\e[5m" # Style: blink
       echo -e "\e[31m" # Text Color: Red
-      echo -e "/ci_tests/${TESTS} is not a valid test directory, Failing"
+      echo -e "CI: /ci_tests/${TESTS} is not a valid test directory, Failing"
       echo -e "\e[0m" # Reset all shell attributes
       exit 1
     fi # end input directory
